name: get_packer_benchmark
description: A high-performance Dart serialization library for efficiently packing and unpacking data, offering a faster and more compact alternative to JSON and MessagePack.
version: 1.0.1
repository: https://github.com/jonataslaw/get_packer

environment:
  sdk: ^3.6.0

dependencies:
  get_packer:
    path: ../
  msgpack_dart: any

dev_dependencies:
  lints: ^6.1.0
  test: ^1.29.0
